[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/l/*"
  to = "/.netlify/functions/l"
  status = 200

[[redirects]]
  from = "/funnel/*"
  to = "/funnel.html"
  status = 200

[[redirects]]
  from = "/bridge/*"
  to = "/bridge.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
